name: Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

    - name: Publish Docker Image to GPR
      uses: sebbrachmann/axn-container-build-publish@master
      with:
        IMAGE_NAME: 'test-docker-action'
        TAG: 'tag-name'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}